#!bin/bash

# export software path to the environment
export PATH=$PATH:/lustre/user/liclab/zhaowx/tools/$software

#wget下载
wget -P /path/to/directory ftp://ftp.sra.ebi.ac.uk/vol1/srr/SRR260/007/SRR2601737

#prefetch下载
prefetch SRA_id -O /path/to/sra

#从集群向服务器远程传输文件
scp ./file zhaowx@hostname:path/to/derectory

#conda create environment -p path/to/derectory python=version
conda create --prefix=/lustre/user/liclab/zhaowx/tools/conda/hicpro python=2.7

#conda install 在指定路径下安装
conda install -p /lustre/user/liclab/zhaowx/tools/conda/hicpro -c bioconda bx-python

# -n 打印出行数 | tail –n 输出后三行 | 输出后三行的第一行
cat –n dd.out | tail –n 3 | head –n 1

#source某个工具
source path/to/app

#比较文件差别
diff

#打印test.txt的第二列
sort -gk2 test.txt | awk '{print$2}'

#建立软链接
ln -s 源文件（夹） 目标文件（夹）
ln -s ln -s /lustre/user/liclab/zhaowx/NuMA/AID/AID-1_combined_R1.fastq.gz .
#在当前文件夹下就会出现一个同名文件，并且建立了软连接AID-1_combined_R1.fastq.gz -> /lustre/user/liclab/zhaowx/NuMA/AID/AID-1_combined_R1.fastq.gz

#压缩/解压缩
tar -zcvf 
tar -zxvf


#vi中途退出到外部命令
!pwd
#通配符
^行首 $行尾 *所有字符（包括空） ?单个字符  !非   ’ 变量名 ’  
ll | grep "^-" | wc -l #统计文件个数
#输出
grep –B10 GGG test.txt 

(cat 1tce.pdb) | grep ARG | while read line ;do echo "zhaowx "$line ;done

cat 1tce.pdb | sed -e 's/ARG/ALA/g' | grep ARG
find /path/to/lib -name file_name

(cat 1tce.pdb) | grep ARG | while read line ;do echo "zhaowx "$line ;done

cat 1tce.pdb | sed -e 's/ARG/ALA/g' | grep ARG
find /path/to/lib -name file_name

#看程序在哪个cpu上跑
cpuidp

#vi块（block）操作
命令模式下用/ ARG可以查找ARG所在位置
Contrl+V 进入块操作
cat 1tce.pdb | grep ARG |sed -e "s/ARG/$a/g"
#打印1tce.pdb文件最后一列
cat 1tce.pdb | awk '{print $NF}' | more
#打印1tce.pdb文件第四列
cat 1tce.pdb | awk '{print $4}' | more

#debug节点上运行命令可以看到程序需要的内存数量
-w指定节点提交
提交脚本命令的时候要加 ./ 
-c 占内存
-n 并行命令核心数
&可以并行处理多个样本

screen –S yourname #新建一个你的名字的session

ssh c07n02n04  #登录到某个节点
free –g #看内存
pstree -apnh JOBID      #查看任务多线程/多进程
pip install –user mpi4py   #安装mpi4py这个库
squene | more   #查看任务号、分区、user time node等信息
sjob JOBID    #查看任务详细信息（root权限可查看脚本）
